
version: '3.8'

services:
  telegram-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./tdlib-db:/app/tdlib-db
      - ./logs:/app/logs
    environment:
      # Configurações de ambiente
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      
      # Credenciais do Telegram (obtenha em https://my.telegram.org/apps)
      - TELEGRAM_API_ID=${TELEGRAM_API_ID:-}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH:-}
      
      # API Key para autenticação da API (deixe em branco para gerar automaticamente)
      - API_KEY=${API_KEY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
